social_media:
  - twitter:
    - name: twitter
    - username: elkcityhazard
    - url: https://twitter.com/elkcityhazard
  - instagram:
    - name: instagram
    - username: elkcityhazard
    - url: https://instagram.com/elkcityhazard